#!/bin/sh

if git rev-parse --verify HEAD >/dev/null 2>&1; then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

clangformat='./clang-format -n -style=file'

# for cpp
info=""
for file in $(git diff-index --name-status $against -- | grep -E '\.[ch](pp)?$' | awk '{print $2}'); do
    cmd="$clangformat $file"
    info="$info$($cmd 2>&1)"
    #echo $cmd
    #echo $info
done

tidy_file() {
    clangtidy="/Users/huweinan/sghwn2/llvm-project-llvmorg-8.0.1/build/bin/clang-tidy -checks=-*,readability-check_namespace_name -p=build/compile_commands.json --quiet"
    info2=""
    for file in $(git diff-index --name-status $against -- | grep -E '\.[ch](pp)?$' | awk '{print $2}'); do
        cmd2="$clangtidy $file"
        info2="$info2$($cmd2)"
        #echo $cmd2
        #echo $info2
    done

    if [ -z "$info2" ]; then
        exit 0
    else
        echo "$info2"
        exit 1
    fi
}

if [ -z "$info" ]; then
    tidy_file
else
    echo "$info"
    exit 1
fi
